spring:
  application:
    name: test_gemini

  ai:
    chat:
      observations:
        log-prompt: false
    openai:
      api-key: ${GEMINI_API_KEY}
      base-url: https://generativelanguage.googleapis.com/v1beta/openai
      chat:
        completions-path: /chat/completions
        options:
          model: gemini-2.5-flash
          temperature: 0.0
      embedding:
        api-key: ${GEMINI_API_KEY}
        base-url: https://generativelanguage.googleapis.com/v1beta/openai
        options:
          model: text-embedding-004
          dimensions: 768
        embeddings-path: /embeddings

    vectorstore:
      simple:
        store:
          path: ./vectorstore.json

  datasource:
    url: jdbc:hsqldb:mem:chatdb
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    username: root
    password:

  sql:
    init:
      mode: always
      schema-locations: classpath:org/springframework/ai/chat/memory/repository/jdbc/schema-hsqldb.sql